version: "3"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8080:8080"
  gps:
    build:
      context: .
      dockerfile: docker/Dockerfile.gps
    ports:
      - "8081:8081"
  rewards:
    build:
      context: .
      dockerfile: docker/Dockerfile.rewards
    ports:
      - "8082:8082"
  pricer:
    build:
      context: .
      dockerfile: docker/Dockerfile.pricer
    ports:
      - "8083:8083"