FROM gradle:7.3.1-jdk11 as builder

WORKDIR /app
COPY ./ /app
RUN gradle build -x test :pricer:bootJar
RUN mv /app/pricer/build/libs/pricer*.jar /app/pricer.jar

FROM openjdk:11-jre-slim

COPY --from=builder /app/pricer.jar pricer.jar
EXPOSE 8080
CMD ["java", "-jar", "pricer.jar"]